---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: NetApp Console 中架構完善的儀表板會掃描系統組態的可靠性、安全性、卓越營運績效、成本最佳化和效能與效率，提供見解和建議，協助您實現卓越營運績效。 
---
= 了解 NetApp Console 中架構完善的儀表板
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Console 中精心設計的儀表板可協助您維護和操作可靠、安全、高效且具成本效益的組態，這些組態與您所使用的儲存設備類型的架構遵守。此儀表板提供跨帳戶和區域的統一檢視，可協助團隊識別風險並確定優先順序，並支援針對特定需求的自訂規則。每日自動掃描您的儲存系統組態，提供洞察和建議，協助您最佳化儲存環境。



[[how-it-works]]
== 運作方式

架構完善的儀表板每日分析您的組態。分析結果提供架構完善的狀態、洞察分析和建議。

每日分析完成後，組態會在架構完善的儀表板中顯示為「最佳化的」或「未最佳化的」。您可以在這裡找到總最佳化得分、按類別劃分的組態問題，以及組態問題和建議清單。您可以審查針對組態問題的建議。某些問題可以由架構完善的儀表板自動修復，而其他問題則需要手動介入。在這種情況下，架構完善的儀表板會提供詳細的說明，幫助您實作建議的變更。

您可以忽略不適用於您環境的組態分析。這樣可以避免不必要的警示和不準確的最佳化結果。當您忽略某個組態分析時，架構完善的儀表板不會將該組態計入總最佳化分數。



[[why-it-matters]]
== 為什麼這很重要

NetApp Console 中架構完善的儀表板將最佳實務應用於大型儲存設備、資料庫和 VMware 環境，透過結合後續評估、建議洞察和修復措施，確保系統穩定運作。架構完善的儀表板所應用的自動化修復功能可減少人為錯誤、確保統一管理，並維護系統基礎架構的效能和可靠性。



[[supported-storage-systems]]
== 支援的儲存系統

Console 中架構完善的儀表板支援以下儲存系統：

* Amazon FSx for NetApp ONTAP
* Microsoft Azure 中的 Cloud Volumes ONTAP




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== 開始使用 NetApp Console 偵測並修正系統組態錯誤

要開始使用 NetApp Console，請註冊、新增憑證並建立連線，以管理您的資源並最佳化系統組態。

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["開始使用 NetApp Console （SaaS 應用程式）的工作流程"^]



[[related-information]]
== 相關資訊

* link:fsx/improve-configurations-fsx.html["為 ONTAP 檔案系統實作架構良好的 FSx"^]
* link:cvo/improve-configurations-cvo.html["實作架構良好的 Cloud Volumes ONTAP 系統"^]

