---
sidebar: sidebar 
permalink: learn-well-architected-dashboard.html 
keywords: well-architected, best practices, well-architected system, best practices, well-architected framework, well-architected configurations, system management, system optimization, system configuration, system analysis 
summary: NetApp Console 中架構完善的儀表板會掃描系統組態的可靠性、安全性、卓越營運績效、成本最佳化和效能與效率，提供見解和建議，協助您實現卓越營運績效。 
---
= 了解 NetApp Console 中架構完善的儀表板
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory 可協助您維護和運作可靠、安全的、高效且具成本效益的組態，這些組態遵守您所使用儲存設備類型的架構完善架構。NetApp Console 中架構完善的儀表板提供跨帳戶和區域的統一檢視，協助團隊識別風險並排定優先順序，並支援針對特定需求的自訂規則。每日自動掃描您的儲存系統組態可提供深入解析與建議，協助您最佳化儲存環境。



[[how-it-works]]
== 運作方式

Workload Factory 每日分析您的組態。此分析提供架構完善的狀態、洞察分析和建議，協助您最佳化儲存環境。

每日分析完成後，組態會在架構完善的儀表板中顯示為「最佳化的」或「未最佳化的」。您可以根據架構完善架構的類別（可靠性、安全性、卓越營運績效、成本最佳化和效能與效率）來尋找組態問題，並查看組態問題清單和建議。Workload Factory 可以自動修復某些問題，而其他問題則需要手動介入。在這種情況下，建議會提供詳細說明，幫助您實作變更。

您可以忽略不適用於您環境的組態分析。忽略組態可避免不必要的警報與不準確的最佳化結果。



[[why-it-matters]]
== 為什麼這很重要

Workload Factory 透過結合後續評估與建議洞察及修復，將最佳實務做法應用於大型儲存設備、資料庫和 VMware 環境。自動化修復可減少人為錯誤、確保統一管理，並維持整個系統基礎架構的效能與可靠性。



[[supported-storage-systems]]
== 支援的儲存系統

Console 中架構完善的儀表板支援以下儲存系統：

* Amazon FSx for NetApp ONTAP
* Microsoft Azure 中的 Cloud Volumes ONTAP




[[get-started-with-netapp-console-to-detect-and-fix-system-misconfigurations]]
== 開始使用 NetApp Console 偵測並修正系統組態錯誤

要開始使用 NetApp Console，請註冊、新增憑證並建立連線，以管理您的資源並最佳化系統組態。

link:http://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["開始使用 NetApp Console （SaaS 應用程式）的工作流程"^]



[[related-information]]
== 相關資訊

* link:fsx/improve-configurations-fsx.html["為 ONTAP 檔案系統實作架構良好的 FSx"^]
* link:cvo/improve-configurations-cvo.html["實作架構良好的 Cloud Volumes ONTAP 系統"^]

