---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, well-architected, well-architected dashboard, amazon fsx for netapp ontap, fsx for ontap, cloud volumes ontap, microsoft azure' 
summary: 透過 NetApp Console 中架構完善的儀表板了解最新功能。 
---
= NetApp Console 中架構完善的儀表板有哪些新功能？
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
透過 NetApp Console 中架構完善的儀表板了解最新功能。



[[17-august-2026]]
== 2026年8月17日



[[google-cloud-netapp-volumes-support-in-the-well-architected-dashboard]]
=== Google Cloud NetApp Volumes 在架構完善的儀表板中的支援

NetApp Console 儀表板現在支援 Google Cloud NetApp Volumes。儲存管理員可以檢視其儲存資源池和組態的狀態，取得有關提升效率、降低成本、提升效能、可靠性和安全性的建議，並採取行動以最佳化作業並遵循最佳實務。

深入瞭解link:https://docs.netapp.com/us-en/console-well-architected/gcnv/configuration-analysis-gcnv.html["Google Cloud NetApp Volumes 組態分析"]。



[[03-august-2026]]
== 2026年8月3日



[[updated-configuration-names-for-fsx-for-ontap-in-the-well-architected-dashboard]]
=== 在架構完善的儀表板中更新了 FSx for ONTAP 的組態名稱

NetApp Console 中架構完善的儀表板現在已更新 FSx for ONTAP 的儲存組態名稱，以提升清晰度和一致性。

下表列出了架構良好的儀表板中的舊組態名稱及其對應的新組態名稱。

[cols="1,1"]
|===
| 舊組態名稱 | 新組態名稱 


| 排程 Volume 備份 | Volume 備份 


| SSD 容量臨界值 | SSD 容量餘裕 


| 檔案容量臨界值 | 檔案容量餘裕 


| 長期保留資料的可靠性 | 複製原則標籤 


| 已排程的本機 Snapshot 快照技術 | Snapshot 原則 


| 刪除不必要的備份 | 備份過期 


| 刪除不必要的 Snapshot 快照技術 | Snapshot 快照技術到期 


| 未充分利用的固態硬碟容量 | 超額配置的 SSD 容量 


| 非作用中區塊設備 | 非作用中區塊設備（LUN） 


| 透過對冷資料分層優化總體擁有成本 | 冷資料分層 


| Volume 邏輯容量報告 | 主機可見容量報告 


| FlexGroup Volume 重新平衡 | 重新平衡 FlexGroup Volume 


| FlexVol® Volume 重新平衡 | 重新平衡 FlexVol® Volume 


| 快取關係寫入模式 | FlexCache® 寫入模式 


| 優化快取磁碟區大小 | FlexCache® 複本大小 


| 未經授權存取 Volume | 未經授權的 iSCSI Volume 存取 


| ARP/AI 已停用 | 勒索軟體保護（ARP/AI） 
|===


[[fix-dismiss-and-reactivate-configurations-for-cloud-volumes-ontap-in-microsoft-azure]]
=== 修正、關閉並重新啟用 Microsoft Azure 中 Cloud Volumes ONTAP 的組態

NetApp Console 中架構完善的儀表板現在可讓您修復 Cloud Volumes ONTAP 系統的組態建議。

您也可以從架構完善的分析中排除一個或多個組態。這樣，您可以忽略不適用於您環境的特定組態。

如果您之後想要納入先前被忽略的組態，可以在架構完善的儀表板中重新啟用它。這樣就能將該組態恢復到分析中，並讓您獲得相關的建議和修復方案。

link:https://docs.netapp.com/us-en/console-well-architected/cvo/\improve-configurations-cvo.html["修正、關閉並重新啟用 Microsoft Azure 中 Cloud Volumes ONTAP 的組態"]



[[20-july-2026]]
== 2026年7月20日



[[introducing-the-well-architected-dashboard-in-netapp-console]]
=== 隆重介紹 NetApp Console 中架構完善的儀表板

NetApp Console 中架構完善的儀表板提供跨帳戶和區域的儲存系統與組態的單一檢視。此儀表板提供各種洞察和建議，協助您實現卓越營運績效。您可以檢視組態的架構完善狀態、依照您所用儲存類型的架構完善架構支柱分類的組態問題，以及組態問題和建議清單。

深入瞭解 link:https://docs.netapp.com/us-en/console-well-architected/learn-well-architected-dashboard.html["架構良好的儀表板"]。

Console 中架構完善的儀表板適用於以下儲存系統：

* link:https://docs.netapp.com/us-en/console-well-architected/fsx/configuration-analysis-fsx.html["Amazon FSx for NetApp ONTAP"]
* link:https://docs.netapp.com/us-en/console-well-architected/cvo/configuration-analysis-cvo.html["Microsoft Azure 中的 Cloud Volumes ONTAP"]




[[build-your-own-custom-rules]]
=== 建立您自己的自訂規則

使用簡明易懂的語言編寫自訂規則，確保您的系統遵循組織的標準和 NetApp 最佳實務做法。先進行模擬執行測試，然後排程規則在您的環境中執行。

https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["深入瞭解自訂規則"]
