---
sidebar: sidebar 
permalink: fsx/configuration-analysis-fsx.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, recommendation, recommendations 
summary: 精心設計的儀表板會定期分析 FSx for ONTAP 檔案系統組態，以確定是否存在任何組態問題。 
---
= Amazon FSx for NetApp ONTAP 組態分析
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp Console 中架構完善的儀表板會定期分析儲存系統組態，以確定您的 Amazon FSx for NetApp ONTAP 檔案系統是否存在任何組態問題。發現問題時，儀表板會顯示問題所在，並說明需要進行哪些變更，以確保您的儲存系統達到最佳效能、具成本效益，並符合最佳實務的法規遵循要求。

主要功能包括：

* 每日配置分析
* 對 NetApp ONTAP 儲存系統和合作夥伴儲存設備提供者進行自動最佳實務做法驗證
* 主動可觀測性
* 洞察化為行動




[[analysis-requirements]]
== 分析要求

要進行完整的檔案系統分析，必須執行以下操作：

* link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html#agent-console-deploy["部署 NetApp Console 代理程式"^] 或 link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["關聯連結"^] 以設定檔案系統與 NetApp Console 之間的連線。
* 在您的 AWS 帳戶中授予 _view、planning 和 analysis_ 權限。
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["了解如何授予 AWS 帳戶權限"^]





[[best-practices-and-recommendations-for-storage-workloads]]
== 儲存工作負載的最佳實務做法和建議

架構完善的儀表板會根據 ONTAP 最佳實務和 AWS Well-Architected Framework 評估儲存組態。此評估也會建議改進措施和修正方法。

精心設計的分析將組態分類為架構的下列要素：_可靠性_、_安全性_、_卓越營運_、_成本最佳化_和_效能效率_。



[[reliability]]
=== 可靠性

可靠性確保工作負載即使在出現中斷的情況下也能正確、持續地執行其預期功能。

* *排程磁碟區備份*
+
備份磁碟區有助於滿足資料保留和合規性需求。使用磁碟區備份來設定資料的自動備份和保留。

* *排程本機快照*
+
安排本機快照以實現高效備份和快速還原。快照是磁碟區的即時時間點映像。

* * 跨區域複寫 *
+
跨區域複寫可確保您的資料複寫到另一個 AWS 區域，從而增強資料持久性和可用度。設定跨區域複寫以支援災難恢復和法規遵循。

* *設定資料複寫*
+
為了提高資料可靠性，請將資料複寫到同一區域或其他區域的 FSx for ONTAP 檔案系統。設定資料複寫以支援跨檔案系統的移轉、災難恢復和長期保留。

* *提高 SSD 容量閾值*
+
SSD 儲存層的容量使用率不得超過 80%。否則可能會影響容量資源池儲存層的資料讀寫，進而影響檔案系統的處理量。當容量耗盡時，資料 Volume 將變為唯讀。嘗試寫入新資料的服務也會失敗。

* *比對標籤以確保資料可靠性*
+
來源磁碟區的快照原則標籤和複寫原則標籤必須相符，以確保資料可靠性。

* *提高檔案容量閾值*
+
應提高檔案容量臨界值，以避免達到 Volume 容量限制。檔案容量（inodes）過低會阻止向 Volume 寫入更多資料。Workload Factory 建議將檔案容量使用率保持在 80% 以下，以允許建立新檔案。





[[security]]
=== 安全性

安全重點在於透過風險評估和緩解策略來保護資料、系統和資產。

* *啟用 ARP/AI*
+
NetApp 具備人工智慧的自主勒索軟體防護（ARP/AI）可協助您保護磁碟區免受勒索軟體威脅。Workload Factory 建議為所有磁碟區啟用 ARP/AI。

* *未經授權存取磁碟區*
+
使用 iSCSI 儲存應用程式資料的 Volume 不應同時允許 NAS 存取。Workload Factory 建議限制 iSCSI Volume 使用任何其他通訊協定。





[[operational-excellence]]
=== 卓越營運

卓越營運的重點在於提供最佳架構和業務價值。

* * 啟用自動容量管理 *
+
應啟用自動容量管理，以定期確保 SSD 層不超過閾值。

* *Volume 容量使用率閾值*
+
Workload Factory 建議 Volume 容量使用率不要超過 80%。這可能會影響應用程式的資料讀寫操作。Volume 容量的增加可以手動進行，也可以使用 Volume 自動擴充功能自動增加。

* *磁碟區使用率接近滿載*
+
當磁碟區接近滿載時、NetApp Workload Factory 建議採取措施增加磁碟區容量、以避免潛在的應用程式中斷。

* *快取關係寫入模式*
+
為了獲得最佳效能， Workload Factory 會根據您的工作負載推薦最合適的快取關係寫入模式。對於讀取密集型、檔案較小的工作負載，環繞寫入模式可提供更佳的效能；而對於寫入密集型、檔案較大的工作負載，回寫模式可提供更佳的效能。

* *最佳化快取磁碟區大小*
+
Workload Factory 建議啟用快取磁碟區的磁碟區自動調整大小和清理功能，以保持最佳大小並將快取集中用於熱資料，從而達到最高效率。

* *Storage VM 邏輯報告*
+
Workload Factory 建議將儲存 VM 的預設報告設定設為邏輯報告，以便更了解磁碟區層級的儲存使用情況。





[[cost-optimization]]
=== 成本最佳化

成本優化可協助您在保持低成本的同時，為企業創造最大價值。

* *透過對冷資料進行分層來優化 TCO*
+
啟用冷資料分層以降低 SSD 儲存層的使用率。Workload Factory 建議對每個 Volume 套用分層原則。FSx for ONTAP 會持續掃描資料中的冷資料，並將其移至容量資源池分層，而不會造成任何中斷。

* *啟用儲存效率*
+
啟用儲存設備效率提升（資料精簡、壓縮和重複資料刪除），以最佳化儲存使用率並降低 SSD 分層成本。

* *不必要的快照和備份刪除*
+
刪除不再需要的快照和備份，以降低成本。

* *非作用中區塊裝置*
+
如果區塊設備連續七天未使用、Workload Factory 建議歸檔區塊設備資料或刪除未使用的區塊設備以降低成本。

* *未充分利用的 SSD 容量*
+
未充分利用的 SSD 容量分層會增加不必要的成本。Workload Factory 建議降低 SSD 分層容量，同時保持 20% 的可用空間緩衝區。容量縮減操作需要數小時到數天時間，在此期間其他檔案系統操作將無法進行。

* *非使用中的 NAS Volume*
+
組態分析會識別未主動使用的 NAS Volume ，並建議刪除或歸檔 Volume 以降低成本。



.接下來
link:improve-configurations-fsx.html["為 ONTAP 檔案系統組態實作架構良好的 FSx"]
